/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package catalog;

public class App {
    public static void main(String[] args) {
        throw new RuntimeException("Method not implemented");
    }
}
